GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO IOMS INDENTIFIED BY ioms;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO IOMS;
CONNECT IOMS/ioms;

CREATE TABLE auth (
	username VARCHAR2(32) PRIMARY KEY,
	pass VARCHAR2(100) NOT NULL,
	userType VARCHAR2(8),
	CUSTOMER_ID NUMBER(3,0),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID NUMBER(3,0) PRIMARY KEY,
	NAME VARCHAR2(32) NOT NULL,
	GENDER VARCHAR2(6),
	PHONE# VARCHAR2(11) NOT NULL UNIQUE,
	DOB DATE,
	ADDRESS VARCHAR2(4000)
);

CREATE TABLE PRODUCTS(
PRD_ID NUMBER(3,0) PRIMARY KEY,
PRD_NAME VARCHAR2(32) NOT NULL,
AVL_QTY NUMBER(3,0) NOT NULL,
B_PRICE NUMBER(5,0),
S_PRICER NUMBER(5,0) NOT NULL)

CREATE TABLE ORDERS (
	ORD_ID NUMBER(4,0) PRIMARY KEY,
	CUSTOMER_ID NUMBER(3,0) NOT NULL,
	ORD_DATE DATE NOT NULL,
	STATUS VARCHAR2(50) NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE PRD_REF (
	ORD_ID NUMBER(4,0) NOT NULL,
	PRD_ID NUMBER(3,0) NOT NULL,
	QTY NUMBER(2,0) NOT NULL,
	FOREIGN KEY (PRD_ID) REFERENCES PRODUCTS(PRD_ID),
	FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);

CREATE TABLE BASKET (
	PRD_ID NUMBER(3,0) NOT NULL,
	QTY NUMBER(2,0) NOT NULL,
	FOREIGN KEY (PRD_ID) REFERENCES PRODUCTS(PRD_ID)
);

CREATE VIEW BASKETVIEW AS
SELECT 
	P.PRD_NAME AS "Item name", 
	P.S_PRICE AS "unit price", 
	B.QTY AS "qty", 
	B.QTY * P.S_PRICE AS "total price"
FROM PRODUCTS P, BASKET B
WHERE B.PRD_ID = P.PRD_ID;

CREATE VIEW CUSTOMERVIEW AS
SELECT 
	C.CUSTOMER_ID, 
	A.USERNAME, 
	C.NAME, 
	C.GENDER, 
	C.PHONE#, 
	TO_CHAR(C.DOB, 'DD-MM-YY') AS DOB, 
	C.ADDRESS
FROM CUSTOMER C, AUTH A
WHERE A.CUSTOMER_ID (+)= C.CUSTOMER_ID;

CREATE VIEW ORDERTABLE AS
SELECT 
	O.ORD_ID, 
	C.NAME AS C_NAME, 
	C.PHONE#, 
	C.ADDRESS AS ADDR, 
	TO_CHAR(O.ORD_DATE, 'DD-MON-YY') AS ORDDATE, 
	O.STATUS
FROM ORDERS O, CUSTOMER C
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID;

CREATE VIEW TO_SHOW_PRD_NAME AS
SELECT DISTINCT 
	R.PRD_ID, 
	P.PRD_NAME
FROM PRD_REF R, PRODUCTS P
WHERE P.PRD_ID = R.PRD_ID;

CREATE VIEW ORDER_HISTORY AS
SELECT 
	O.ORD_ID, 
	R.PRD_ID, 
	P.PRD_NAME, 
	R.QTY, 
	O.ORD_DATE, 
	O.STATUS
FROM ORDERS O, PRD_REF R, TO_SHOW_PRD_NAME P
WHERE O.ORD_ID = R.ORD_ID AND P.PRD_ID = R.PRD_ID
ORDER BY ORD_ID;

CREATE VIEW ORDER_ACTIVE AS
SELECT 
	O.ORD_ID, 
	R.PRD_ID, 
	P.PRD_NAME, 
	R.QTY, 
	O.ORD_DATE, 
	O.STATUS
FROM ORDERS O, PRD_REF R, TO_SHOW_PRD_NAME P
WHERE O.ORD_ID = R.ORD_ID AND P.PRD_ID = R.PRD_ID AND O.STATUS = 'PENDING'
ORDER BY ORD_ID;