GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO IOMS IDENTIFIED BY ioms;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO IOMS;
CONNECT IOMS/ioms;

CREATE TABLE "CUSTOMER" 
(
	"CUSTOMER_ID" NUMBER(3,0), 
	"NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(6), 
	"PHONE#" VARCHAR2(11) NOT NULL ENABLE, 
	"DOB" DATE, 
	"ADDRESS" VARCHAR2(4000), 
	PRIMARY KEY ("CUSTOMER_ID") ENABLE, 
	UNIQUE ("PHONE#") ENABLE
);
CREATE TABLE "AUTH" 
(
	"USERNAME" VARCHAR2(50), 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	"USERTYPE" VARCHAR2(6) NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(3,0), 
	PRIMARY KEY ("USERNAME") ENABLE, 
	FOREIGN KEY ("CUSTOMER_ID")
	REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE
);
CREATE TABLE "PRODUCTS" 
(
	"PRD_ID" NUMBER(3,0), 
	"PRD_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"AVL_QTY" NUMBER(3,0) NOT NULL ENABLE, 
	"B_PRICE" NUMBER(5,0), 
	"S_PRICE" NUMBER(5,0) NOT NULL ENABLE, 
	PRIMARY KEY ("PRD_ID") ENABLE
);

CREATE TABLE "ORDERS" 
(
	"ORD_ID" NUMBER(4,0), 
	"CUSTOMER_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"ORD_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	PRIMARY KEY ("ORD_ID") ENABLE, 
	FOREIGN KEY ("CUSTOMER_ID")
	REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE
);

CREATE TABLE "PRD_REF" 
(
	"ORD_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"PRD_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"QTY" NUMBER(2,0) NOT NULL ENABLE, 
	FOREIGN KEY ("PRD_ID")
	REFERENCES "PRODUCTS" ("PRD_ID") ENABLE, 
	FOREIGN KEY ("ORD_ID")
	REFERENCES "ORDERS" ("ORD_ID") ENABLE
);

CREATE OR REPLACE FORCE VIEW "BASKETVIEW" ("Item_name", "unit_price", "qty", "total_price") AS 
SELECT P.PRD_NAME, P.S_PRICE, B.QTY, B.QTY * P.S_PRICE 
FROM PRODUCTS P, BASKET B 
WHERE B.PRD_ID = P.PRD_ID;

CREATE OR REPLACE FORCE VIEW "CUSTOMERVIEW" ("CUSTOMER_ID", "USERNAME", "NAME", "GENDER", "PHONE#", "DOB", "ADDRESS") AS 
SELECT C.CUSTOMER_ID, NVL(A.USERNAME, '-'), C.NAME, C.GENDER, C.PHONE#, TO_CHAR(C.DOB, 'DD-MM-YY') AS DOB, C.ADDRESS
FROM CUSTOMER C, AUTH A
WHERE A.CUSTOMER_ID(+) = C.CUSTOMER_ID;

CREATE OR REPLACE FORCE VIEW  "ORDERTABLE" ("ORD_ID", "C_NAME", "PHONE#", "ADDR", "ORDDATE", "STATUS") AS 
SELECT O.ORD_ID, C.NAME, C.PHONE#, C.ADDRESS, TO_CHAR(O.ORD_DATE,'DD-MON-YY') AS ORDDATE, O.STATUS
FROM ORDERS O, CUSTOMER C
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID;

CREATE OR REPLACE FORCE VIEW  "TO_SHOW_PRD_NAME" ("PRD_ID", "PRD_NAME") AS 
  SELECT DISTINCT R.PRD_ID, P.PRD_NAME
FROM PRD_REF R, PRODUCTS P
WHERE P.PRD_ID=R.PRD_ID;

CREATE OR REPLACE FORCE VIEW  "ORDER_ACTIVE" ("ORD_ID", "PRD_ID", "PRD_NAME", "QTY", "ORD_DATE", "STATUS") AS 
  SELECT O.ORD_ID, R.PRD_ID,P.PRD_NAME, R.QTY, O.ORD_DATE, O.STATUS
FROM ORDERS O, PRD_REF R, TO_SHOW_PRD_NAME P
WHERE O.ORD_ID=R.ORD_ID AND P.PRD_ID = R.PRD_ID AND O.STATUS = 'PENDING'
ORDER BY ORD_ID;

CREATE OR REPLACE FORCE VIEW  "ORDER_HISTORY" ("ORD_ID", "PRD_ID", "PRD_NAME", "QTY", "ORD_DATE", "STATUS") AS 
  SELECT O.ORD_ID, R.PRD_ID,P.PRD_NAME, R.QTY, O.ORD_DATE, O.STATUS
FROM ORDERS O, PRD_REF R, TO_SHOW_PRD_NAME P
WHERE O.ORD_ID=R.ORD_ID AND P.PRD_ID = R.PRD_ID
ORDER BY ORD_ID;